spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    org.jooq.tools.LoggerListener: DEBUG
    org.springframework.transaction.interceptor: TRACE